workflows:
    sample-workflow:
        name: Codemagic Pli Bubbles workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: pli_bubbles_api_key
        environment:
          ios_signing:
            distribution_type: app_store
            bundle_identifier: com.plibubblesapp.PliBubbles
            vars:
                APP_STORE_APPLE_ID: 6753183931
        scripts:
          - name: Increment build number
            script: | 
              #!/bin/sh
              cd $CM_BUILD_DIR
              LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
              agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          - name: Build ipa for distribution
